language: android
# Use the Travis Container-Based Infrastructure
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.gradle/wrapper
env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
    # Latest revision of Android SDK Tools
    - tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-22
    - android-25

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
# Emulator Management: Create, Start and Wait
before_script:
  - chmod +x gradlew
  # Emulator creates a 32MB SD card file to store cucumber html/json reports
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c 32M
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  # ARM emulator is very slow to start without hardware acceleration
  - sleep 200
  - adb devices
  - adb shell settings put global window_animation_scale 0
  - adb shell settings put global transition_animation_scale 0
  - adb shell settings put global animator_duration_scale 0
  - adb shell input keyevent 82 &
script:
  - ./gradlew check connectedCheck -PdisablePreDex
after_script:
  - echo "Travis TRAVIS_BUILD_DIR:"${TRAVIS_BUILD_DIR}
  - cat ${TRAVIS_BUILD_DIR}/app/build/outputs/lint-results-debug.html
  - head -200 ${TRAVIS_BUILD_DIR}/app/build/outputs/androidTest-results/connected/*
